application:
  security:
    jwt:
      secret-key: 574E635266556A586E3272357538782FG13F4428472B4B6250645367066B5879
      expiration: 604800000 #7 days
      refresh-token:
        expiration: 1209600000 #14 days

otp:
  length: 6
  expiration: 15 #minutes

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profolio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: profol.io@outlook.com
    password: Mastodon2023
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

gcp:
  config:
    file: gcp-account-info.json
  project:
    id: western-throne-404921
  bucket:
    id: profolio-media-bucket
  dir:
    name: user-data
